<?php namespace ProcessWire;

use Youshido\GraphQL\Type\Object\ObjectType;
use Youshido\GraphQL\Type\InputObject\InputObjectType;
use Youshido\GraphQL\Type\Scalar\FloatType;
use Youshido\GraphQL\Type\Scalar\IntType;
use Youshido\GraphQL\Type\Scalar\StringType;
use ProcessWire\Page;
use ProcessWire\Field;

class FieldtypeMapMarkerGraphQL extends WireData implements Module {

  /**
   * getModuleInfo is a module required by all modules to tell ProcessWire about them
   *
   * @return array
   *
   */
  public static function getModuleInfo() {

    return array(

      // The module's title, typically a little more descriptive than the class name
      'title' => 'FieldtypeMapMarkerGraphQL', 

      // version number 
      'version' => 0, 

      // summary is brief description of what this module is
      'summary' => 'GraphQL support for FieldtypeMapMarker.',
      
      // Optional URL to more information about the module
      'href' => 'https://github.com/dadish/FieldtypeMapMarkerGraphQL',
    
      // Optional font-awesome icon name, minus the 'fa-' part
      'icon' => 'map',

      'requires' => ['ProcessGraphQL']
      );
  }

  public static function getType(Field $field)
  {
    return new ObjectType([
      'name' => 'MapMarker',
      'fields' => [
        'lat' => [
          'type' => new FloatType(),
          'description' => 'The latitude of the MapMarker.',
          'resolve' => function ($value) {
            return (float) $value->lat;
          }
        ],

        'lng' => [
          'type' => new FloatType(),
          'description' => 'The longitude of the MapMarker.',
          'resolve' => function ($value) {
            return (float) $value->lng;
          }
        ],

        'address' => [
          'type' => new StringType(),
          'description' => 'The address of the MapMarker.',
          'resolve' => function ($value) {
            return (string) $value->address;
          }
        ],

        'zoom' => [
          'type' => new IntType(),
          'description' => 'The zoom of the MapMarker.',
          'resolve' => function ($value) {
            return (integer) $value->zoom;
          }
        ],
      ],
    ]);
  }

  public static function getInputType(Field $field)
  {
    return new InputObjectType([
      'name' => 'MapMarkerInput',
      'fields' => [
        'lat' => new FloatType(),
        'lng' => new FloatType(),
        'address' => new stringType(),
        'zoom' => new IntType(),
      ],
    ]);
  }

  public static function setValue(Page $page, Field $field, $value)
  {
    $fieldName = $field->name;
    $page->$fieldName->lat = $value['lat'];
    $page->$fieldName->lng = $value['lng'];
    $page->$fieldName->address = $value['address'];
    $page->$fieldName->zoom = $value['zoom'];    
  }
}
